# Copyright (c) 2019, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: java

jdk:
  - oraclejdk8

dist: trusty

cache:
  directories:
  - "$HOME/.m2"

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  - wget http://ballerina-distributions.private.wso2.com/2019-09-03/1.0.0-beta/ballerina-linux-installer-x64-1.0.0-beta.deb
  - sudo dpkg -i ballerina-linux-installer-x64-1.0.0-alpha3.deb

addons:
  apt:
    packages:
      - oracle-java8-installer

install: true

script: mvn clean install
